### PR TITLE
Contrib/issue 173 bidirectional search play around

### PR DESCRIPTION
**Pull request by vtelensky**
# List of things I have found and I would like to discuss:

1. In class hipster-core/src/main/java/es/usc/citius/hipster/algorithm/BSStar.java I was receiving NullPointerException in cases when  open[d].poll(); returns null. Variable current was null and it fails on first calling of current.state(). I tried to treat this situation. Can you look at it and tell me if that was right approach?

2.  I think that calling of Hipster.createBSStar(searchProblem).search("Some node name") doesn't make a sense for bidirectional algorithm. I tried to specify the Predicate but I don't know how it should look like. I know that Bidirectional algorihm should terminate when both ends meets in one node somwhere in the graph. But for that case we would need to identify such a node. Can we store this somehwere into node instance? Into which class we should add this information? Do you know some better approach how to terminate algorithm?

3. I don't think that right now there is good support of building result path for bidirectional algorithm. As we are building according states of goal nodes. I think that after ending of bidirectional algorithm we have store only one half of finded path in goalNodes. There should be some way how to recover whole path from both searching ends. Do you know how we could process recovering right path?

Maybe some of the listed points are nonsense because of my little knowledge of hipster4j and the algorithm. So please be a patient with me. I just try to understand :).

### CODE REVIEW

**Comment by pablormier** [comment]
Hi @D3ryk 

Thank you so much for your detailed analysis of the BS* implementation. As you realized, some of the design decisions that we adopted in the first versions of the library are not the best ones to fit algorithms like this one, and the work you did here will help us to better understand how to change things to make hipster4j more simple and easy to extend. We're pretty busy right now but we'll review your work and we'll give you feedback as soon as we can.

I would like to thank you again for your work and interest. And BTW, happy new year!

**Comment by vtelensky** [comment]
Hi @pablormier 

Thanks for reply. Once you will review my analysis, feel free to give me some other task :).

Happy new year to you as well :).

**Comment by vtelensky** [comment]
Hi @pablormier 

Did you have a chance to review my analysis?

**Comment by pablormier** [comment]
Hi @D3ryk 

Didn't forget :). I haven't had much time since I'm involved in other higher priority tasks, but I was thinking of reviewing this in two weeks (~February 24th/25th). 

Thanks for your understanding

**Comment by vtelensky** [comment]
Hi, how this looks? Is there anything I could contrib?

**Pull request closed without merging**
